### ISSUE TITLE
Can't build a Docker image for this action

### ISSUE THREAD

**Issue by MaxDesiatov** [NSHipster/update-homebrew-formula-action#1]
It fails to build from `Dockerfile` with this error:

```
  Step 1/9 : FROM ruby:2.7-alpine
   ---> 79f5adf3c887
  Step 2/9 : RUN apk --update add --no-cache --virtual run-dependencies build-base
   ---> Using cache
   ---> 289b16cb0fec
  Step 3/9 : COPY LICENSE.md README.md /
   ---> Using cache
   ---> d3b96ad7bb75
  Step 4/9 : COPY Homebrew /Homebrew
   ---> Using cache
   ---> 77a330a1c9e9
  Step 5/9 : COPY Gemfile /
   ---> Using cache
   ---> 8f67a614f2df
  Step 6/9 : RUN bundle install -j 8
   ---> Running in 404f4149796a
  Your Gemfile has no gem server sources. If you need gems that are not already on
  your machine, add a line like this to your Gemfile:
  source 'https://rubygems.org'
  Could not find gem 'parser (~> 2.7.1)' in any of the gem sources listed in your
  Gemfile.
```

Example CI run with this failure: https://github.com/swiftwasm/carton/runs/1293640656?check_suite_focus=true

**Comment by mattt** [comment]
It looks like this is a git submodules issue. The project includes Homebrew as a submodule, and `Gemfile` transcludes / subsumes / or whatever that project's `Gemfile` to invoke the equivalent of `brew style` via Rubocop. Lemme see where I'm missing the required `git submodule` incantation.

**Comment by mattt** [comment]
<del>Apparently the solution is not what you might expect: https://stackoverflow.com/questions/58690455/how-to-correctly-initialize-git-submodules-in-dockerfile-for-docker-cloud<del>

<ins>Edit:</ins> Actually, that's not quite what we want. That's specific to Docker <del>Hub</del> <ins>wait, what's Docker _Cloud_</ins>?

**Comment by MaxDesiatov** [comment]
Cool, thanks for the update!

**Comment by mattt** [comment]
@MaxDesiatov Please give it another try and let me know if you're still having issues. Thanks!

**Comment by MaxDesiatov** [comment]
Will do! Just managed it all manually for this release. The action is already there in our workflow and will be auto-triggered with the next release. Well let you know if I see any problems. Thanks again!
