### ISSUE TITLE
Bottle artifacts with `.1` in their name not being detected

### ISSUE THREAD

**Issue by MaxDesiatov** [NSHipster/update-homebrew-formula-action#12]
For some reason [a few runs of this action](https://github.com/swiftwasm/carton/runs/1499137031?check_suite_focus=true) produced an artifact with name `carton--0.9.0.catalina.bottle.1.tar.gz` instead of `carton--0.9.0.catalina.bottle.tar.gz`. I also got this behavior of `brew` reproduced locally. Additionally, running `brew bottle` after such build locally then adds `rebuild 1` key, which I guess indicates that the artifact was attempted to rebuild at least once?

```ruby
  bottle do
    root_url "https://homebrew.bintray.com/bottles-tap"
    cellar :any_skip_relocation
    rebuild 1
    sha256 "868e223ffa7bf2d221540d6a82db2e5b279c1bbd399e704a153d8b02964ff8cb" => :big_sur
  end
```

Either way, because of this uploads of the artifact fail. Would it be hard to implement detection of such rebuilds and make the action more resilient to this kind of behavior?

Thanks!

**Comment by mattt** [comment]
> Would it be hard to implement detection of such rebuilds and make the action more resilient to this kind of behavior?

@MaxDesiatov Not at all! It should be pretty straightforward. Please give #13 a try when you have a chance.

**Comment by MaxDesiatov** [comment]
Probably with the next release, but the PR seems legit to me, so I wouldn't mind if it's merged now 🙂

**Comment by MaxDesiatov** [comment]
Thanks for the quick fix! 👍

**Comment by mattt** [comment]
Welp, here goes nothing. Gotta love flying blind without any tests.

**Comment by MaxDesiatov** [comment]
Maybe a mock repository could be set up with a mock formula to test this end-to-end?

**Comment by mattt** [comment]
That's a possibility, though we'd have to reckon with a host of problems around global mutable state. I wonder if we could set up and tear down a unique test repo on each run? 🤔
