### ISSUE TITLE
Version specified in the formula is not updated

### ISSUE THREAD

**Issue by MaxDesiatov** [NSHipster/update-homebrew-formula-action#7]
See https://github.com/swiftwasm/homebrew-tap/commit/1189847e57f7ca68a39495117f30da242bee4055 commit by the action, the download url is updated, but `version "0.8.1"` line is not.

**Comment by mattt** [comment]
@MaxDesiatov Aw, that's frustrating. Apparently I've been writing formulas this whole time without thinking to specify a `version`. This should be fixed by #8.
