### ISSUE TITLE
Error pushing bottle with this action

### ISSUE THREAD

**Issue by renehernandez** [NSHipster/update-homebrew-formula-action#9]
I am following the example you provided in the docs to bottle a formula and update the downstream tap, but it fails with the following error:

```shell
Error: Container action is only supported on Linux
```

Github Action run with the failure: https://github.com/renehernandez/appfile/runs/1480833469?check_suite_focus=true

**Comment by MaxDesiatov** [comment]
You need to specify `runs-on: ubuntu-latest` to use this formula. Container actions can't be run on macOS GitHub Actions agents.

**Comment by renehernandez** [comment]
In the Readme example at [updating-a-formula-with-a-bottle](https://github.com/NSHipster/update-homebrew-formula-action#updating-a-formula-with-a-bottle) the job specifies `runs-on: macos-10.15`

**Comment by renehernandez** [comment]
> You need to specify `runs-on: ubuntu-latest` to use this formula. Container actions can't be run on macOS GitHub Actions agents.

Does it means, that I will need to cache the generated bottle file and run the action to update the tap on another job (running on ubuntu?

**Comment by MaxDesiatov** [comment]
In my understanding yes, but maybe @mattt can clarify it.

**Comment by renehernandez** [comment]
If that is the case, then the example in Readme should be updated to reflect the correct usage. Once I get it working I'll submit a PR

**Comment by mattt** [comment]
@renehernandez Thanks for reporting this. Unfortunately, testing GitHub Actions is proving to be difficult, and I haven't had much bandwidth to invest in a reasonable solution.

I just opened #10 which should (🤞) work. If you have some time, would you be able to re-run with this to confirm that it resolves your issue?

**Comment by renehernandez** [comment]
Testing it now

**Comment by renehernandez** [comment]
The change you suggested fixes the issue of running the job 👍 !! 

Though I ran into another issue it seems, the formula file is not being update with the bottle information.

Github Action run: https://github.com/renehernandez/appfile/actions/runs/396906682
Formula in tap repo: https://github.com/renehernandez/homebrew-taps/blob/main/Formula/appfile.rb

**Comment by renehernandez** [comment]
@mattt Should I open a new issue about my last comment?

**Comment by mattt** [comment]
@renehernandez Thanks so much for confirming the fix!

I have a theory about what caused your last run to fail, which #11 may address (namely, a disparity in the `v` prefix for tag name and semantic version). Whenever it's convenient, could you re-run against `NSHipster/update-homebrew-formula-action@fix-bottle-regex`?

If that doesn't fix it, we can open up a new issue thread to track this.

**Comment by renehernandez** [comment]
> Whenever it's convenient, could you re-run against `NSHipster/update-homebrew-formula-action@fix-bottle-regex`?

I'll take a look and get back to you later today

**Comment by renehernandez** [comment]
So, I ran it again with your branch, but it still shows the same issue:

* Github Action run: https://github.com/renehernandez/appfile/runs/1524502784?check_suite_focus=true
* Workflow: https://github.com/renehernandez/appfile/blob/main/.github/workflows/release_brew.yml
* Tap: https://github.com/renehernandez/homebrew-taps/blob/main/Formula/appfile.rb

**Comment by renehernandez** [comment]
@mattt Should we continue on a new Issue?

**Comment by mattt** [comment]
@renehernandez I just successfully<sup>*</sup> ran it with the latest HEAD on `main` https://github.com/NSHipster/homebrew-formulae/commit/c780bc082b3f89580849ba6a457c242ec9158b4a. If you're still having problems, please open a new issue. Thanks again for your help tracking this down.

<sup>*</sup> The workflow is failing on `workflows/upload-release-asset` with "Error: request to [...] failed, reason: socket hang up" (https://github.com/actions/upload-release-asset/issues/69 🤷‍♂️.
